
== Second HTML based Open-Dolphin Example Application

In contrast to the first example application this one connects to a JEE based server.
Again it is very simple and focuses on the parts you need to provide to make
the browser talk to the application on the server.

Note that you can implement the server part with other frameworks like Grails for example but since this is
shown already with the demos coming with open-dolphin I decided to take a JEE based approach (you need at least JEE6 support for this example).

First you need a servlet which inherits from DolphinServlet. In the first example application the text of the label was extended in the browser.
In this example this should happen on the server side because this is real business logic and therefore belongs on the server :-)
So when the button in the browser is clicked a command 'makeItLonger' should be sent to the server which in turn extends the value of the PM's attribute.
Since open-dolphin always keeps the PMs of the client and server in sync (so called shared presentation models) the change will be visible immediately
on the client. Note that we do not have to program anything to make this happen.

Here is the servlet which registers our single action:
[source,java]
----
package org.opendolphin.odwebjee;

import javax.servlet.annotation.WebServlet;
import org.opendolphin.core.server.ServerDolphin;
import org.opendolphin.server.adapter.DolphinServlet;

@WebServlet(urlPatterns = {"/dolphin"})
public class MyDolphinServlet extends DolphinServlet {

    @Override
    protected void registerApplicationActions(final ServerDolphin serverDolphin) {
        serverDolphin.register(new MakeItLongerAction());
    }
}
----


and the action:
[source,java]
----
package org.opendolphin.odwebjee;

import org.opendolphin.core.server.ServerAttribute;
import org.opendolphin.core.server.ServerPresentationModel;
import org.opendolphin.core.server.action.DolphinServerAction;
import org.opendolphin.core.server.comm.ActionRegistry;
import org.opendolphin.core.server.comm.SimpleCommandHandler;

/**
 * Simple Action to demonstrate how a PM-attribute is modified and the
 * change is immediately visible on the client.
 */
public class MakeItLongerAction extends DolphinServerAction {

    @Override
    public void registerIn(ActionRegistry registry) {

        // Register CommandHandler under the name 'makeItLonger':
        registry.register("makeItLonger", new SimpleCommandHandler() {

            @Override
            public void handleCommand() {
                // Get a handle to the PM which was initially created by the client (see index.html):
                ServerPresentationModel pm = getServerDolphin().getAt("myPM");

                // get the PM's attribute 'myAttribute':
                final ServerAttribute at = pm.getAt("myAttribute");

                // Change the value of the attribute. change is immediately visible on the client:
                changeValue(at, at.getValue() + " longer");
            }
        });

    }
}
----

The only difference in the html is that we create a dolphin instance with the URL of our servlet and in the
button click handler we send the command to the server:

[source,javascript]
----
	const dolphin = dol.dolphin(window.location + "/dolphin", true);
	//...
	myButton.onclick = function () {
		dolphin.send("makeItLonger");
	};

----

== Run it
E.g. with Netbeans:

* open project (pom.xml) in NetBeans
* Run Project 'odwebjee'
* open browser at: http://localhost:8080/od_web_02_remote_mode_jee/
* click button 'make string longer on server'
* text of label below button shows: 'longer longer longer...' (one more 'longer ' each time you click the button)
