
= Simple JS using webjars

Simple _Hello world_ example using HTML and Javascript as client.
Therefore only the modules _server_, _shared_ and _webapp_ are needed.

== Usage

* clone repo
* `cd webapp`
* `./gradlew :appRun`
* point your browser to http://localhost:8080/appContext/hellodolphin.jsp

== opendolphin.js as artifact

`opendolphin.js` is used via webjar (see dependency in build.gradle: `compile 'org.open-dolphin:client-javascript:0.12.0B2'`)
This way javascript resources can be used from our gradle build process
just like mavenrepository artifacts (usually jar files).
And this also means that we do not have to pollute our source repositories anymore with these artifacts.

From HTML you refer to `opendolphin.js` like this:

[source,html]
----
<script type="text/javascript" src="webjars/org/opendolphin/0.12.0B2/opendolphin.js"></script>
----

BTW: bootstrap is used via webjar as well.

== Additional Info

To keep things simple a JSP is used since that is supported by Jetty out of the box.
You could also use a simple html file if you replace the values in `webapp/js/app/api.js.jsp` with
the appropriate values.

