
= Simple JS

Simple _Hello world_ example using HTML and Javascript as client.
Therefore only the modules _server_, _shared_ and _webapp_ are needed.

== opendolphin.js as artifact

`opendolphin-<version>.js` is downloaded automatically on the fly during the
build process from https://bintray.com/opendolphin/resources/opendolphin/view#files[bintray].
This way javascript resources can be used from our gradle build process
just like use mavenrepository artifacts (usually jar files).
And this also means that we do not have to pollute our source repositories anymore with these artifacts.

To be able to do this in your project you need to apply the following changes to your `build.gradle` file (see `webapp/build.gradle`):

* add a repository definition to opendolphin on bintray `webapp/build.gradle`
* add a configuration for the artifacts
* add a new task `fetchWebappArtifacts` which downloads the artifacts
* let existing tasks like `war` depende on the new task.

Here is how it looks like in our example:

[source,groovy]
----
include::webapp/build.gradle
----


== Additional Info

To keep things simple a JSP is used since that is supported by Jetty out of the box.
You could also use a simple html file if you replace the values in `webapp/js/app/api.js.jsp` with
the appropriate values.

